var __extends=this.__extends||function(k,b){function g(){this.constructor=k}g.prototype=b.prototype;k.prototype=new g},hrfm;
(function(k){var b=function(){};b.WHEEL="";b.RESIZE="";b.START="";b.MOVE="";b.END="";b.CANCEL="";b.TRNEND="";b.TOUCH_SUPPORTED=null;b.initialize=function(a,c,h){b.TOUCH_SUPPORTED=a;b.WHEEL=h?"DOMMouseScroll":"mousewheel";b.RESIZE="onorientationchange"in window?"orientationchange":"resize";b.START=a?"touchstart":"mousedown";b.MOVE=a?"touchmove":"mousemove";b.END=a?"touchend":"mouseup";b.CANCEL=a?"touchcancel":"mouseup";b.TRNEND=!1===c?!1:{"":"transitionend",webkit:"webkitTransitionEnd",Moz:"transitionend",
O:"otransitionend",ms:"MSTransitionEnd"}[c]};b.bind=function(a,c,h,d){"undefined"===typeof d&&(d=!1);a.addEventListener(c,h,d)};b.unbind=function(a,c,h,d){"undefined"===typeof d&&(d=!1);a.removeEventListener(c,h,d)};b.click=function(a){if("fireEvent"in a)a.fireEvent("onclick");else if("function"===typeof a.click)a.click();else{var c=document.createEvent("MouseEvents");c.initEvent("click",!1,!0);a.dispatchEvent(c)}};k.Event=b;var g,e=function(a,c,h){"undefined"===typeof c&&(c=void 0);"undefined"===
typeof h&&(h=0);this.id=e._ID++;this._f=a;this._s=c;this.priority=h};e._ID=0;e.prototype.e=function(a){"undefined"===typeof a&&(a=null);return!1==this._f.call(this._s,a)?null:this.n};e.prototype.eq=function(a,c){"undefined"===typeof c&&(c=void 0);return a==this._f&&c==this._s};g=e;k.Closure=g;var f=function(){};f.prototype.add=function(a,c,h){"undefined"===typeof c&&(c=void 0);"undefined"===typeof h&&(h=0);var d,b;if(this.head){d=this.head;for(b=null;d;){if(d.eq(a,c))return-1;!b&&d.priority<h&&(b=
d);d=d.n}d=new g(a,c,h);b?b.p?(a=b.p,b.p=d,d.n=b,d.p=a,a.n=d):(b.p=d,d.n=b,this.head=d):(b=this.tail,b.n=d,d.p=b,this.tail=d)}else this.head=this.tail=d=new g(a,c,h);return d.id};f.prototype.rm=function(a,c){"undefined"===typeof c&&(c=void 0);for(var b=this.head;b;){if(b.eq(a,c)){this._rm(b);break}b=b.n}};f.prototype.rmById=function(a){for(var c=this.head;c;){if(c.id==a){this._rm(c);break}c=c.n}};f.prototype.rmAll=function(){for(var a=this.head;a;)a=a.n;this.tail=this.head=null};f.prototype.exec=
function(a){"undefined"===typeof a&&(a=void 0);if(this.head){var c=this.head;if("undefined"===typeof a)for(;c;)c=c.e();else for(;c;)c=c.e(a)}};f.prototype._rm=function(a){this.head==a?this.tail==a?this.tail=this.head=null:(this.head=a.n,a.n.p=null):this.tail==a?(this.tail=a.p,a.p.n=null):(a.p.n=a.n,a.n.p=a.p)};k.ClosureList=f;var j=function(){this._hash_=[]};j.prototype.on=function(a,c,b,d){"undefined"===typeof b&&(b=this);"undefined"===typeof d&&(d=0);var g,e=a.split(" "),j=e.length;for(a=0;a<j;a++)g=
e[a],this._hash_[g]||(this._hash_[g]=new f),this._hash_[g].add(c,b,d);return this};j.prototype.onWithId=function(a,c,b,d){"undefined"===typeof b&&(b=this);"undefined"===typeof d&&(d=0);this._hash_[a]||(this._hash_[a]=new f);return this._hash_[a].add(c,b,d)};j.prototype.off=function(a,b,g){"undefined"===typeof b&&(b=void 0);"undefined"===typeof g&&(g=this);if("number"===typeof a)for(var d in this._hash_)this._hash_[d].rmById(a);else if("string"===typeof a){var e=a.split(" "),f=e.length;for(a=0;a<f;a++)d=
e[a],this._hash_[d]&&("undefined"===typeof b?this._hash_[d].rmAll():this._hash_[d].rm(b,g))}return this};j.prototype.execute=function(a,b){"undefined"===typeof b&&(b=null);this._hash_[a]&&this._hash_[a].exec(b)};j.prototype.removeAllListeners=function(){for(var a in this._hash_)this._hash_[a].rmAll();this._hash_=[]};k.EventDispatcher=j})(hrfm||(hrfm={}));
var Cycle=function(k){function b(b){"undefined"===typeof b&&(b=0);k.call(this);this.running=!1;this.interval=b;this.initialTime=(new Date).getTime();this.elapsedTime=0;this._requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b){return setTimeout(b,17)};this._cancelAnimationFrame=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||
window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout}__extends(b,k);b.prototype.start=function(){if(!0!=this.running){var b=this,e=0,f=(new Date).getTime(),j=0,a=this.interval;this._onAnimate=0<a?function(){e=(new Date).getTime();100*a<e-f&&(f=e-a);j=e-f;if(a<j){var c=~~(j/a);f+=c*a;b.execute("cycle",c)}b.elapsedTime+=j;b._animateID=b._requestAnimationFrame.call(window,b._onAnimate)}:function(){e=(new Date).getTime();j=e-f;
b.elapsedTime+=j;b.execute("cycle",1);f=e;b._animateID=b._requestAnimationFrame.call(window,b._onAnimate)};this._animateID=this._requestAnimationFrame.call(window,b._onAnimate);this.running=!0;this.execute("start")}};b.prototype.stop=function(){!1!=this.running&&(this._onAnimate=function(){},this._cancelAnimationFrame.call(window,this._animateID),this.running=!1,this.execute("stop"))};return b}(hrfm.EventDispatcher);
